// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

library FarmingErrors {

    uint16 constant SENDER__ONLY_SENDER__ERROR = 1101;
    uint16 constant SENDER__ONLY_OWNER_OR_SENDER__ERROR = 1102;
    uint16 constant SENDER__SENDER_NOT_EXISTS__ERROR = 1103;

    uint16 constant FARMING__AMOUNT_TOO_SMALL__ERROR = 1001;
    uint16 constant FARMING__DEPOSIT_EXISTS_ALREADY__ERROR = 1002;
    uint16 constant FARMING__TOKEN_BALANCE_NOT_ENOUGH__ERROR = 1003;
    uint16 constant FARMING__REQUEST_NOT_EXISTS__ERROR = 1004;
    uint16 constant FARMING__REQUEST_EXECUTED_ALREADY__ERROR = 1005;
    uint16 constant FARMING__POSITION_AMOUNT_NOT_ENOUGH__ERROR = 1006;
    uint16 constant FARMING__TOKEN_AMOUNTS_NOT_EQUALS__ERROR = 1007;
    uint16 constant FARMING__VALUE_NOT_ENOUGH__ERROR = 1008;
    uint16 constant FARMING__REQUEST_EXISTS_ALREADY__ERROR = 1009;
    uint16 constant FARMING__LP_AMOUNT_TOO_DIG__ERROR = 1010;
    uint16 constant FARMING__TRANSFER_REQUEST__ERROR = 1011;
    uint16 constant FARMING__ZERO_ADDRESS__ERROR = 1012;
    uint16 constant FARMING__LP_TOKEN_SET_ALREADY__ERROR = 1013;
    uint16 constant FARMING__ONLY_FARMING_MANIPULATOR__ERROR = 1014;
    uint16 constant FARMING__LP_TOKEN_NOT_SET__ERROR = 1015;
    uint16 constant FARMING__WRONG_CLIENT_ADDRESS__ERROR = 1016;
    uint16 constant FARMING__CLIENT_NOT_FOUND__ERROR = 1017;
    uint16 constant FARMING__NON_CONTRACT__ERROR = 1018;
    uint16 constant FARMING__CALLDATA__ERROR = 1019;
    uint16 constant FARMING__ONLY_PROXY_APPROVER__ERROR = 1020;
    uint16 constant FARMING__PROXY_APPROVER_SET_ALREADY__ERROR = 1021;
    uint16 constant FARMING__DEPOSIT_APPROVE_EXISTS_ALREADY__ERROR = 1022;
    uint16 constant FARMING__DEPOSIT_APPROVE_NOT_FOUND__ERROR = 1023;
    uint16 constant FARMING__DEPOSIT_APPROVE_EXECUTED_ALREADY__ERROR = 1024;
    uint16 constant FARMING__WRONG_REFUNDING_TOKEN_ADDRESS__ERROR = 1025;
    uint16 constant FARMING__ONLY_LP_TOKEN__ERROR = 1026;
}
